Material från Stanford CS231n: http://cs231n.github.io/python-numpy-tutorial/#numpy

# NumPy

NumPy provides an efficient way to store and manipulate multi-dimensional dense arrays in Python. 

The important features of NumPy are:

* It provides an ndarray structure, which allows efficient storage and manipulation of vectors, matrices, and higher-dimensional datasets.
* It provides a readable and efficient syntax for operating on this data, from simple element-wise arithmetic to more complicated linear algebraic operations.

In the simplest case, NumPy arrays look a lot like Python lists.

### Arrays 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [1]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
a = np.array([1, 2, 3]); a  # Create a rank 1 array

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape           

(3,)

In [5]:
print(a[0], a[1], a[2])

1 2 3


In [6]:
a[0] = 5; a                 # Change an element of the array

array([5, 2, 3])

In [7]:
b = np.array([[1,2,3],[4,5,6]]); b    # Create a rank 2 array

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b.shape

(2, 3)

In [9]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


### Functions to construct arrays

Numpy also provides many functions to create arrays:

In [10]:
a = np.zeros((2,2));a

array([[0., 0.],
       [0., 0.]])

In [11]:
b = np.ones((1,2));b    # Create an array of all ones

array([[1., 1.]])

In [ ]:
q = np.ones((2));q

In [12]:
c = np.full((2,2), 7); c  # Create a constant array

array([[7, 7],
       [7, 7]])

In [13]:
d = np.eye(4);d        # Create a 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array indexing
 

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array

Create a rank 2 array with shape (3, 4)

In [14]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]);a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Use slicing to pull out the subarray consisting of the first 2 rows
and columns 1 and 2; b is the following array of shape (2, 2):

In [15]:
b = a[:2, 1:3]; b

array([[2, 3],
       [6, 7]])

Numpy provides many useful functions for performing computations on arrays; one of the most useful is sum:

In [16]:
x = np.array([[1,2],[3,4]]); x

array([[1, 2],
       [3, 4]])

In [17]:
np.sum(x)  # Compute sum of all elements

10

In [18]:
np.sum(x, axis=0) # Compute sum of each column


array([4, 6])

In [19]:
np.sum(x, axis=1)  # Compute sum of each row

array([3, 7])

### Array math 

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [20]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
x
y

array([[1., 2.],
       [3., 4.]])

array([[5., 6.],
       [7., 8.]])

Elementwise sum

In [21]:
x + y
np.add(x,y)

array([[ 6.,  8.],
       [10., 12.]])

array([[ 6.,  8.],
       [10., 12.]])

Elementwise difference

In [ ]:
x - y
np.subtract(x,y)

Elementwise product

In [ ]:
x * y
np.multiply(x, y)

Elementwise division

In [ ]:
x / y
np.divide(x, y)

We use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [22]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

x
y
v
w

array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([ 9, 10])

array([11, 12])

Inner product of vectors

In [23]:
v.dot(w)
np.dot(v, w)

219

219

Matrix / vector product

In [24]:
x.dot(v)
np.dot(x, v)

array([29, 67])

array([29, 67])

Matrix / matrix product

In [25]:
x.dot(y)
np.dot(x, y)

array([[19, 22],
       [43, 50]])

array([[19, 22],
       [43, 50]])

http://matrixmultiplication.xyz/

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

We will add the vector v to each row of the matrix x,
storing the result in the matrix y

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
x
v
y

Add the vector v to each row of the matrix x with an explicit loop

In [ ]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [ ]:
y

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
y = x + v
y